version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_todo
    restart: always
    environment:
      MYSQL_DATABASE: ToDoDb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: tecni-devops/Dockerfile
    container_name: todo_app
    ports:
      - "5000:80"
    depends_on:
      - mysql
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mysql;Port=3306;Database=ToDoDb;User=user;Password=password;

volumes:
  db_data:
