name: CI/CD

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  build-test:
    runs-on: ubuntu-20.04

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: tododb
        ports:
          - 3308:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Install libssl1.1 (required for .NET Core 3.1)
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl1.1

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 3.1.x

      - name: Restaurar dependencias
        run: dotnet restore

      - name: Compilar
        run: dotnet build --no-restore

      - name: Ejecutar tests
        run: dotnet test --no-build --verbosity normal

  docker:
    needs: build-test
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build y push de imagen
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/tecni-devops:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/tecni-devops:latest
